name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Pure:
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        std: [98, 11, 14, 17, 20]
        config: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      #- run: cmake -S. -B ./build_98_pure -D GLM_TEST_ENABLE_CXX_98=ON -DGLM_TEST_FORCE_PURE=ON -DCMAKE_BUILD_TYPE=${{matrix.config}}
      - run: cmake -S. -B ./build_auto -DCMAKE_BUILD_TYPE=${{matrix.config}}
      - run: cmake --build ./build_auto --parallel --config ${{matrix.config}}
      - run: ctest --parallel 4 --verbose -C ${{matrix.config}} --test-dir ./build_auto

#name: GLM Unit Tests

#run-name: ${{ github.actor }} is running GLM unit tests

#on:
#    push:
#    pull_request:
#        branches:
#            - master

#jobs:
#  windows-latest:
#    runs-on: windows-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        std: [98, 11, 14, 17, 20]
        #os: [ubuntu-latest, macos-latest, windows-latest]
#        config: [Debug, Release]

#    name: "${{ matrix.os}} ${{ matrix.cxx }} C++:${{ matrix.std }}"
#    runs-on: ubuntu-latest, macos-latest, windows-latest
#    env:
#      CXX: ${{ matrix.cxx }}

#    steps:
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v4
#      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "ğŸ This job's status is ${{ job.status }}."

#      - name: Tool versions
#        run: |
#          ${CXX} --version
#          cmake --version

      #- run: cmake --build . --parallel --config ${{matrix.config}}
      #- run: ctest --parallel 4 --verbose -C ${{matrix.config}}